### ISSUE TITLE
Tooltip error

### ISSUE THREAD

**Issue by Mattsingen** [MightyPirates/Vials#2]
I've added vials to my personal pack as it looks interesting. Vials-MC1.11.2-1.2.0.1.jar
My second problem is that there is a tooltip error.

The following is added to the client log:
`[17:57:31] [Client thread/ERROR] [jei/]: Failed to get tooltip: 1xitem.vials.vial_144@0 vials:vial_144
java.lang.NullPointerException`

I'm playing on a server with forge-1.11.2-13.20.0.2311

If you need any more information I'll be happy to try and give you what's needed.

**Comment by lordjoda** [comment]
Sry for the late response. I tried to reproduce the exception, but did not manage to do so. Could you tell me how to reproduce the problem?

**Comment by Mattsingen** [comment]
I've tried to recreate the issue on a clean install and failed. Removed and added back Vials on my server and now it works. Must have been something gone corrupt.
Sorry for wasting your time :(

Keep up the great work, I really like the mod!!!
